# Site settings
title: カリ工大 - karitech
email: shigekikarita@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  blog on machine learning and computer science.
#baseurl: "/blog/" # the subpath of your site, e.g. /blog/

baseurl: "/blog"
url: "http://shigekikarita.github.io/blog" # the base hostname & protocol for your site
twitter_username: kari_tech
github_username:  ShigekiKarita

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

#markdown: kra

highlighter: pygments

gems:
    - jekyll-gist
