# Site settings
title: memo and tips
email: shigekikarita@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  blog on machine learning and computer science.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ShigekiKarita
github_username:  ShigekiKarita

# Build settings
markdown: kramdown
